apiVersion: v1
kind: Service
metadata:
    name: database-service
spec:
    type: NodePort
    ports:
      - targetPort: 3306
        port: 3306
        #        nodePort: 30009
    selector:
        name: mysqldb
